--
-- PostgreSQL database dump
--

\restrict SspFafX7AkOvlekRxLu62om7wZyz6isWpvZdfaKUhp69iOoA4V6Qiajugd8AnaI

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-01-23 08:59:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 24576)
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 16421)
-- Name: customer_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_user (
    customer_id integer NOT NULL,
    first_name character varying,
    last_name character varying,
    middle_name character varying,
    company_name character varying,
    email character varying,
    phone character varying,
    landline character varying,
    username character varying,
    password character varying,
    verification_status character varying,
    approved boolean,
    verified_at timestamp without time zone,
    verified_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.customer_user OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16420)
-- Name: customer_user_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer_user ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_user_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16412)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    dept_id integer NOT NULL,
    dept_name character varying
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16411)
-- Name: department_dept_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN dept_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_dept_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16390)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    employee_id integer NOT NULL,
    firstname character varying,
    lastname character varying,
    middlename character varying,
    role_id integer,
    department_id integer,
    username character varying,
    password character varying,
    email character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16389)
-- Name: employee_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16481)
-- Name: machine_brochures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machine_brochures (
    brochure_id integer NOT NULL,
    machine_id integer,
    title character varying,
    file_url character varying,
    uploaded_at timestamp without time zone
);


ALTER TABLE public.machine_brochures OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16480)
-- Name: machine_brochures_brochure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machine_brochures ALTER COLUMN brochure_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_brochures_brochure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16472)
-- Name: machine_gallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machine_gallery (
    gallery_id integer NOT NULL,
    machine_id integer,
    image_url character varying,
    caption character varying,
    uploaded_at timestamp without time zone
);


ALTER TABLE public.machine_gallery OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16471)
-- Name: machine_gallery_gallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machine_gallery ALTER COLUMN gallery_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_gallery_gallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16463)
-- Name: machine_manuals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machine_manuals (
    manual_id integer NOT NULL,
    machine_id integer,
    title character varying,
    file_url character varying,
    uploaded_at timestamp without time zone
);


ALTER TABLE public.machine_manuals OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16462)
-- Name: machine_manuals_manual_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machine_manuals ALTER COLUMN manual_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_manuals_manual_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16499)
-- Name: machine_specifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machine_specifications (
    spec_id integer NOT NULL,
    machine_id integer,
    spec_name character varying,
    spec_value character varying
);


ALTER TABLE public.machine_specifications OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16498)
-- Name: machine_specifications_spec_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machine_specifications ALTER COLUMN spec_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_specifications_spec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16490)
-- Name: machine_videos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machine_videos (
    video_id integer NOT NULL,
    machine_id integer,
    video_type character varying,
    title character varying,
    video_url character varying,
    uploaded_at timestamp without time zone
);


ALTER TABLE public.machine_videos OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16489)
-- Name: machine_videos_video_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machine_videos ALTER COLUMN video_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machine_videos_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16443)
-- Name: machines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.machines (
    machine_id integer NOT NULL,
    customer_id integer,
    product_id integer,
    serial_number character varying,
    model_number character varying,
    purchase_date timestamp without time zone,
    registration_date timestamp without time zone,
    status character varying,
    created_at timestamp without time zone
);


ALTER TABLE public.machines OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16442)
-- Name: machines_machine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.machines ALTER COLUMN machine_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machines_machine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16454)
-- Name: parts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parts (
    parts_id integer NOT NULL,
    parts_name character varying,
    product_id integer,
    description character varying,
    price numeric,
    stock_quantity integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.parts OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16453)
-- Name: parts_parts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parts ALTER COLUMN parts_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parts_parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16508)
-- Name: parts_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parts_request (
    request_id integer NOT NULL,
    customer_id integer,
    machine_id integer,
    status character varying,
    payment_verified boolean,
    payment_proof_url character varying,
    verified_by integer,
    call_verified boolean,
    call_verified_at timestamp without time zone,
    total_amount numeric,
    notes character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.parts_request OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16517)
-- Name: parts_request_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parts_request_items (
    item_id integer NOT NULL,
    request_id integer,
    parts_id integer,
    quantity integer,
    unit_price numeric,
    subtotal numeric
);


ALTER TABLE public.parts_request_items OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16516)
-- Name: parts_request_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parts_request_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parts_request_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 16507)
-- Name: parts_request_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parts_request ALTER COLUMN request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parts_request_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16434)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    product_id integer NOT NULL,
    product_name character varying,
    product_desc character varying,
    created_at timestamp without time zone
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16433)
-- Name: product_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 16535)
-- Name: quote_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quote_items (
    item_id integer NOT NULL,
    quote_id integer,
    parts_id integer,
    quantity integer,
    unit_price numeric,
    subtotal numeric
);


ALTER TABLE public.quote_items OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 16534)
-- Name: quote_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quote_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 16526)
-- Name: quote_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quote_request (
    quote_id integer NOT NULL,
    customer_id integer,
    status character varying,
    total_amount numeric,
    notes character varying,
    submitted_at timestamp without time zone,
    approved_at timestamp without time zone,
    approved_by integer
);


ALTER TABLE public.quote_request OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 16525)
-- Name: quote_request_quote_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quote_request ALTER COLUMN quote_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quote_request_quote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16403)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_name character varying
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 16544)
-- Name: shipment_tracking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipment_tracking (
    tracking_id integer NOT NULL,
    request_id integer,
    courier_type character varying,
    tracking_number character varying,
    status character varying,
    picked_up_at timestamp without time zone,
    delivered_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.shipment_tracking OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 16543)
-- Name: shipment_tracking_tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shipment_tracking ALTER COLUMN tracking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_tracking_tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4886 (class 2606 OID 16430)
-- Name: customer_user customer_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_user
    ADD CONSTRAINT customer_user_email_key UNIQUE (email);


--
-- TOC entry 4888 (class 2606 OID 16428)
-- Name: customer_user customer_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_user
    ADD CONSTRAINT customer_user_pkey PRIMARY KEY (customer_id);


--
-- TOC entry 4890 (class 2606 OID 16432)
-- Name: customer_user customer_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_user
    ADD CONSTRAINT customer_user_username_key UNIQUE (username);


--
-- TOC entry 4883 (class 2606 OID 16419)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (dept_id);


--
-- TOC entry 4874 (class 2606 OID 16401)
-- Name: employee employee_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_email_key UNIQUE (email);


--
-- TOC entry 4876 (class 2606 OID 16397)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (employee_id);


--
-- TOC entry 4878 (class 2606 OID 16399)
-- Name: employee employee_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_username_key UNIQUE (username);


--
-- TOC entry 4904 (class 2606 OID 16488)
-- Name: machine_brochures machine_brochures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_brochures
    ADD CONSTRAINT machine_brochures_pkey PRIMARY KEY (brochure_id);


--
-- TOC entry 4902 (class 2606 OID 16479)
-- Name: machine_gallery machine_gallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_gallery
    ADD CONSTRAINT machine_gallery_pkey PRIMARY KEY (gallery_id);


--
-- TOC entry 4900 (class 2606 OID 16470)
-- Name: machine_manuals machine_manuals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_manuals
    ADD CONSTRAINT machine_manuals_pkey PRIMARY KEY (manual_id);


--
-- TOC entry 4908 (class 2606 OID 16506)
-- Name: machine_specifications machine_specifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_specifications
    ADD CONSTRAINT machine_specifications_pkey PRIMARY KEY (spec_id);


--
-- TOC entry 4906 (class 2606 OID 16497)
-- Name: machine_videos machine_videos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_videos
    ADD CONSTRAINT machine_videos_pkey PRIMARY KEY (video_id);


--
-- TOC entry 4894 (class 2606 OID 16450)
-- Name: machines machines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_pkey PRIMARY KEY (machine_id);


--
-- TOC entry 4896 (class 2606 OID 16452)
-- Name: machines machines_serial_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_serial_number_key UNIQUE (serial_number);


--
-- TOC entry 4898 (class 2606 OID 16461)
-- Name: parts parts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT parts_pkey PRIMARY KEY (parts_id);


--
-- TOC entry 4912 (class 2606 OID 16524)
-- Name: parts_request_items parts_request_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request_items
    ADD CONSTRAINT parts_request_items_pkey PRIMARY KEY (item_id);


--
-- TOC entry 4910 (class 2606 OID 16515)
-- Name: parts_request parts_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request
    ADD CONSTRAINT parts_request_pkey PRIMARY KEY (request_id);


--
-- TOC entry 4892 (class 2606 OID 16441)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (product_id);


--
-- TOC entry 4916 (class 2606 OID 16542)
-- Name: quote_items quote_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quote_items
    ADD CONSTRAINT quote_items_pkey PRIMARY KEY (item_id);


--
-- TOC entry 4914 (class 2606 OID 16533)
-- Name: quote_request quote_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quote_request
    ADD CONSTRAINT quote_request_pkey PRIMARY KEY (quote_id);


--
-- TOC entry 4880 (class 2606 OID 16410)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4918 (class 2606 OID 16551)
-- Name: shipment_tracking shipment_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment_tracking
    ADD CONSTRAINT shipment_tracking_pkey PRIMARY KEY (tracking_id);


--
-- TOC entry 4920 (class 2606 OID 24615)
-- Name: shipment_tracking shipment_tracking_request_id_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment_tracking
    ADD CONSTRAINT shipment_tracking_request_id_unique UNIQUE (request_id);


--
-- TOC entry 4884 (class 1259 OID 16659)
-- Name: dept_dept_name_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX dept_dept_name_key ON public.department USING btree (dept_name);


--
-- TOC entry 4881 (class 1259 OID 16658)
-- Name: roles_role_name_key; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX roles_role_name_key ON public.roles USING btree (role_name);


--
-- TOC entry 4923 (class 2606 OID 16562)
-- Name: customer_user customer_user_verified_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_user
    ADD CONSTRAINT customer_user_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.employee(employee_id);


--
-- TOC entry 4921 (class 2606 OID 16557)
-- Name: employee employee_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.department(dept_id);


--
-- TOC entry 4922 (class 2606 OID 16552)
-- Name: employee employee_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- TOC entry 4929 (class 2606 OID 16592)
-- Name: machine_brochures machine_brochures_machine_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_brochures
    ADD CONSTRAINT machine_brochures_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(machine_id);


--
-- TOC entry 4928 (class 2606 OID 16587)
-- Name: machine_gallery machine_gallery_machine_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_gallery
    ADD CONSTRAINT machine_gallery_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(machine_id);


--
-- TOC entry 4927 (class 2606 OID 16582)
-- Name: machine_manuals machine_manuals_machine_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_manuals
    ADD CONSTRAINT machine_manuals_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(machine_id);


--
-- TOC entry 4931 (class 2606 OID 16602)
-- Name: machine_specifications machine_specifications_machine_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_specifications
    ADD CONSTRAINT machine_specifications_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(machine_id);


--
-- TOC entry 4930 (class 2606 OID 16597)
-- Name: machine_videos machine_videos_machine_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machine_videos
    ADD CONSTRAINT machine_videos_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(machine_id);


--
-- TOC entry 4924 (class 2606 OID 16567)
-- Name: machines machines_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_user(customer_id);


--
-- TOC entry 4925 (class 2606 OID 16572)
-- Name: machines machines_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id);


--
-- TOC entry 4926 (class 2606 OID 16577)
-- Name: parts parts_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT parts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id);


--
-- TOC entry 4932 (class 2606 OID 16607)
-- Name: parts_request parts_request_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request
    ADD CONSTRAINT parts_request_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_user(customer_id);


--
-- TOC entry 4935 (class 2606 OID 16627)
-- Name: parts_request_items parts_request_items_parts_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request_items
    ADD CONSTRAINT parts_request_items_parts_id_fkey FOREIGN KEY (parts_id) REFERENCES public.parts(parts_id);


--
-- TOC entry 4936 (class 2606 OID 16622)
-- Name: parts_request_items parts_request_items_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request_items
    ADD CONSTRAINT parts_request_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.parts_request(request_id);


--
-- TOC entry 4933 (class 2606 OID 16612)
-- Name: parts_request parts_request_machine_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request
    ADD CONSTRAINT parts_request_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(machine_id);


--
-- TOC entry 4934 (class 2606 OID 16617)
-- Name: parts_request parts_request_verified_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parts_request
    ADD CONSTRAINT parts_request_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.employee(employee_id);


--
-- TOC entry 4939 (class 2606 OID 16647)
-- Name: quote_items quote_items_parts_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quote_items
    ADD CONSTRAINT quote_items_parts_id_fkey FOREIGN KEY (parts_id) REFERENCES public.parts(parts_id);


--
-- TOC entry 4940 (class 2606 OID 16642)
-- Name: quote_items quote_items_quote_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quote_items
    ADD CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quote_request(quote_id);


--
-- TOC entry 4937 (class 2606 OID 16637)
-- Name: quote_request quote_request_approved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quote_request
    ADD CONSTRAINT quote_request_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employee(employee_id);


--
-- TOC entry 4938 (class 2606 OID 16632)
-- Name: quote_request quote_request_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quote_request
    ADD CONSTRAINT quote_request_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_user(customer_id);


--
-- TOC entry 4941 (class 2606 OID 16652)
-- Name: shipment_tracking shipment_tracking_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment_tracking
    ADD CONSTRAINT shipment_tracking_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.parts_request(request_id);


-- Completed on 2026-01-23 08:59:05

--
-- PostgreSQL database dump complete
--

\unrestrict SspFafX7AkOvlekRxLu62om7wZyz6isWpvZdfaKUhp69iOoA4V6Qiajugd8AnaI

