CREATE TABLE "employee" (
  "employee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar,
  "lastname" varchar,
  "middlename" varchar,
  "role_id" int,
  "department_id" int,
  "username" varchar UNIQUE,
  "password" varchar,
  "email" varchar UNIQUE,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar
);

CREATE TABLE "department" (
  "dept_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dept_name" varchar
);

CREATE TABLE "customer_user" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "middle_name" varchar,
  "company_name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "landline" varchar,
  "username" varchar UNIQUE,
  "password" varchar,
  "verification_status" varchar,
  "approved" boolean,
  "verified_at" timestamp,
  "verified_by" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "product" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar,
  "product_desc" varchar,
  "created_at" timestamp
);

CREATE TABLE "machines" (
  "machine_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "product_id" int,
  "serial_number" varchar UNIQUE,
  "model_number" varchar,
  "purchase_date" timestamp,
  "registration_date" timestamp,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "parts" (
  "parts_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parts_name" varchar,
  "product_id" int,
  "description" varchar,
  "price" decimal,
  "stock_quantity" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "machine_manuals" (
  "manual_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "machine_id" int,
  "title" varchar,
  "file_url" varchar,
  "uploaded_at" timestamp
);

CREATE TABLE "machine_gallery" (
  "gallery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "machine_id" int,
  "image_url" varchar,
  "caption" varchar,
  "uploaded_at" timestamp
);

CREATE TABLE "machine_brochures" (
  "brochure_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "machine_id" int,
  "title" varchar,
  "file_url" varchar,
  "uploaded_at" timestamp
);

CREATE TABLE "machine_videos" (
  "video_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "machine_id" int,
  "video_type" varchar,
  "title" varchar,
  "video_url" varchar,
  "uploaded_at" timestamp
);

CREATE TABLE "machine_specifications" (
  "spec_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "machine_id" int,
  "spec_name" varchar,
  "spec_value" varchar
);

CREATE TABLE "parts_request" (
  "request_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "machine_id" int,
  "status" varchar,
  "payment_verified" boolean,
  "payment_proof_url" varchar,
  "verified_by" int,
  "call_verified" boolean,
  "call_verified_at" timestamp,
  "total_amount" decimal,
  "notes" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "parts_request_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" int,
  "parts_id" int,
  "quantity" int,
  "unit_price" decimal,
  "subtotal" decimal
);

CREATE TABLE "quote_request" (
  "quote_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "status" varchar,
  "total_amount" decimal,
  "notes" varchar,
  "submitted_at" timestamp,
  "approved_at" timestamp,
  "approved_by" int
);

CREATE TABLE "quote_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quote_id" int,
  "parts_id" int,
  "quantity" int,
  "unit_price" decimal,
  "subtotal" decimal
);

CREATE TABLE "shipment_tracking" (
  "tracking_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" int UNIQUE,
  "courier_type" varchar,
  "tracking_number" varchar,
  "status" varchar,
  "picked_up_at" timestamp,
  "delivered_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "employee" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "employee" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("dept_id");

ALTER TABLE "customer_user" ADD FOREIGN KEY ("verified_by") REFERENCES "employee" ("employee_id");

ALTER TABLE "machines" ADD FOREIGN KEY ("customer_id") REFERENCES "customer_user" ("customer_id");

ALTER TABLE "machines" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

ALTER TABLE "parts" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

ALTER TABLE "machine_manuals" ADD FOREIGN KEY ("machine_id") REFERENCES "machines" ("machine_id");

ALTER TABLE "machine_gallery" ADD FOREIGN KEY ("machine_id") REFERENCES "machines" ("machine_id");

ALTER TABLE "machine_brochures" ADD FOREIGN KEY ("machine_id") REFERENCES "machines" ("machine_id");

ALTER TABLE "machine_videos" ADD FOREIGN KEY ("machine_id") REFERENCES "machines" ("machine_id");

ALTER TABLE "machine_specifications" ADD FOREIGN KEY ("machine_id") REFERENCES "machines" ("machine_id");

ALTER TABLE "parts_request" ADD FOREIGN KEY ("customer_id") REFERENCES "customer_user" ("customer_id");

ALTER TABLE "parts_request" ADD FOREIGN KEY ("machine_id") REFERENCES "machines" ("machine_id");

ALTER TABLE "parts_request" ADD FOREIGN KEY ("verified_by") REFERENCES "employee" ("employee_id");

ALTER TABLE "parts_request_items" ADD FOREIGN KEY ("request_id") REFERENCES "parts_request" ("request_id");

ALTER TABLE "parts_request_items" ADD FOREIGN KEY ("parts_id") REFERENCES "parts" ("parts_id");

ALTER TABLE "quote_request" ADD FOREIGN KEY ("customer_id") REFERENCES "customer_user" ("customer_id");

ALTER TABLE "quote_request" ADD FOREIGN KEY ("approved_by") REFERENCES "employee" ("employee_id");

ALTER TABLE "quote_items" ADD FOREIGN KEY ("quote_id") REFERENCES "quote_request" ("quote_id");

ALTER TABLE "quote_items" ADD FOREIGN KEY ("parts_id") REFERENCES "parts" ("parts_id");

ALTER TABLE "shipment_tracking" ADD FOREIGN KEY ("request_id") REFERENCES "parts_request" ("request_id");
